// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: '1:769020150328:web:0fd51c5ab618a1c6a0dccd',
    messagingSenderId: '769020150328',
    projectId: 'fleettrackingmaster',
    authDomain: 'fleettrackingmaster.firebaseapp.com',
    storageBucket: 'fleettrackingmaster.appspot.com',
    measurementId: 'G-9G5WVZ741H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_API_KEY'
    appId: '1:769020150328:android:4e09b450c3581d75a0dccd',
    messagingSenderId: '769020150328',
    projectId: 'fleettrackingmaster',
    storageBucket: 'fleettrackingmaster.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_API_KEY'
    appId: '1:769020150328:ios:719b899077513fdba0dccd',
    messagingSenderId: '769020150328',
    projectId: 'fleettrackingmaster',
    storageBucket: 'fleettrackingmaster.appspot.com',
    iosBundleId: 'com.example.fleettrackingmaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_API_KEY'
    appId: '1:769020150328:ios:719b899077513fdba0dccd',
    messagingSenderId: '769020150328',
    projectId: 'fleettrackingmaster',
    storageBucket: 'fleettrackingmaster.appspot.com',
    iosBundleId: 'com.example.fleettrackingmaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_API_KEY'
    appId: '1:769020150328:web:d57c9197177459fca0dccd',
    messagingSenderId: '769020150328',
    projectId: 'fleettrackingmaster',
    authDomain: 'fleettrackingmaster.firebaseapp.com',
    storageBucket: 'fleettrackingmaster.appspot.com',
    measurementId: 'G-DWZ1X5KBSG',
  );
}
